name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create deployment package
        run: |
          mkdir package
          pip install -r requirements.txt -t package
          cp lambda_function.py package/
          cd package
          zip -r9 ../lambda_function.zip .
          cd ..

      - name: Upload deployment package
        uses: actions/upload-artifact@v2
        with:
          name: lambda-deployment
          path: lambda_function.zip

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
        run: |
          aws lambda update-function-code --function-name your_lambda_function_name --zip-file fileb://lambda_function.zip
