name: "Halt for Approval"

on:
  workflow_dispatch:

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for High/Critical Issues
        id: detect
        run: |
          # Simulate detection of critical issues
          echo "High/Critical issues detected."
          exit 1  # Exit on failure

  approval:
    runs-on: ubuntu-latest
    needs: check_issues
    if: failure()  # Runs only if check_issues fails
    steps:
      - name: Await Manual Approval
        uses: hmarr/auto-approve-action@v2
        with:
          approver: Furkhanhash
          reason: "High/Critical issues detected. Please review and approve."

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy
        run: echo "Deploying application..."
