name: "Pause and Approve Pipeline"

on:
  push:
    branches:
      - main

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for High/Critical Issues
        run: |
          echo "Checking for high/critical issues..."
          # Simulate detection of issues
          exit 1  # Fail if issues are detected

  manual_approval:
    runs-on: ubuntu-latest
    needs: check_issues
    if: failure()  # Only run if check_issues fails
    steps:
      - name: Await Manual Approval
        run: echo "High/critical issues detected. Please approve to continue."

  deploy:
    runs-on: ubuntu-latest
    needs: manual_approval
    steps:
      - name: Deploy Application
        run: echo "Deploying application..."
