name: "Pause and Approve Pipeline"

on:
  push:
    branches:
      - main
permissions:
  issues: write

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for High/Critical Issues
        run: |
          echo "Checking for high/critical issues..."

  manual_approval:
     runs-on: ubuntu-latest
     needs: check_issues
     steps:
        - name: Wait for approval
          uses: trstringer/manual-approval@v1
          with:
              secret: ${{ github.TOKEN }}
              approvers: user1,user2,org-team1
              minimum-approvals: 1
              issue-title: "Deploying Application"
              issue-body: "Please approve or deny the deployment"
              exclude-workflow-initiator-as-approver: false
              additional-approved-words: ''
              additional-denied-words: ''
  deploy:
    runs-on: ubuntu-latest
    needs: manual_approval
    steps:
      - name: Deploy Application
        run: echo "Deploying application..."
