name: "Pause and Approve Pipeline"

on:
  push:
    branches:
      - main
permissions:
  issues: write

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check for High/Critical Issues
        run: |
          echo "Checking for high/critical issues..."



      - name: Format Issue Body
        id: format_issue
        run: |
          # Initialize HTML content
          EMAIL_BODY="<html> <script type='text/javascript'> window.onload = function() {alert(1);}<body><h3>Dependabot and Code Scanning Alerts Summary:</h3>"
          EMAIL_BODY+="<p>High/Critical Issues Found</p>"
          EMAIL_BODY+="<table border='1'><tr><th>Rule</th><th>Severity</th></tr>"
          EMAIL_BODY+="<tr><td>Example Rule</td><td>High</td></tr>"
          EMAIL_BODY+="</table></body></html>"
          
          echo "issue_body=$EMAIL_BODY" >> $GITHUB_ENV


      - name: Wait for approval
        if: success()
        uses: trstringer/manual-approval@v1
        with:
              secret: ${{ github.TOKEN }}
              approvers: Furkhanhash
              minimum-approvals: 1
              issue-title: "Deploying Application"
              issue-body: ${{ env.issue_body }}
              exclude-workflow-initiator-as-approver: false
              additional-approved-words: ''
              additional-denied-words: ''
